language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - build-tools-28.0.0
    - android-28

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
