language: android
android:
  components:
    - android-28
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.0

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
